; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:default]

platform = espressif32@6.12.0
board = esp32dev
framework = arduino

monitor_filters = 
	time
	log2file

lib_deps =
    https://github.com/Giddy-Up224/esp_log_alias.git#1.0.0 ; Logging lib wrapper
    # Add your library dependencies here

build_flags = 
    ; Change this log level to whatever your logging needs are
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG